export enum StaffCategory {
    CHEF = 'CHEF',
    ACCOUNTANT='ACCOUNTANT',
    CLEARNER = 'CLEARNER',
    DELIVER = 'DELIVER',
    MANAGER = 'MANAGER',
    SECURITY = 'SECURITY',
    WARITER = 'WARITER',
}